config/routes.rb
Dreamscape::Application.routes.draw do

  resources :tasks, :only => [:edit, :update, :create, :destroy]
  resources :dreams, :only => [:edit, :update, :create, :destroy]
  resources :collaborations, :only => ['create', 'destroy']
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "pages/index"
  post "pages/index"
  root :to => 'pages#index'
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, :dependent => :destroy
  has_many :collaborations, :dependent => :destroy
  has_many :collaborators, :through => :collaborations, :source => :collaborator

  accepts_nested_attributes_for :tasks
  validates :user_id, :presence => true
  validates :title,   :presence => true

  def add_collaborator!(collaborator)
    collaborations.create!(:collaborator_id => collaborator.id)
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_filter :init_facebook_oauth, :force_facebook_auth, :init_facebook_crap

  def create
    @dream = current_user.dreams.build(params[:dream])
    if @dream.save
      redirect_to root_path, :flash => { :success => "Dream created!" }
    else
      @dreams = current_user.dreams.all(:include => 'tasks')
      @task = Task.new
      render 'pages/index'
    end
  end

  def edit
    @dream = current_user.dreams.find(params[:id])
  end

  def update
    @dream = current_user.dreams.find(params[:id])
    if @dream.update_attributes(params[:dream])
      flash[:success] = "Dream updated."
      redirect_to '/pages/index'
    else
      render 'edit'
    end
  end

  def destroy
    @dream = current_user.dreams.find_by_id(params[:id])
    @dream.destroy
    redirect_to root_path, :flash => {:success => "Dream deleted!"}
  end
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/_dream.html.haml
%h3{:class => "cloud round"}= dream.title
=link_to "Edit", edit_dream_path(dream)
=link_to "Delete", dream, :method => :delete
- if dream.completed?
  =link_to "Incomplete", {:controller => "dreams", :action => "update", "dream" => {:completed => false}, :id => dream.id}, :method => :put
- else
  =link_to "Complete", {:controller => "dreams", :action => "update", "dream" => {:completed => true}, :id => dream.id}, :method => :put
%br
%br
%h4{:class => "task_header"} Tasks
%div{:class => "tasks"}= render dream.tasks
= form_for(@task) do |f|
  = render('shared/error_messages', :object => f.object) if @task.dream == dream
  .field
    = f.text_area :title, :class => "round"
    = f.hidden_field :dream_id, :value => dream.id
    = f.submit "Add Task"
%br

app/views/dreams/edit.html.haml
= form_for(@dream) do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.label :title
    %br
    = f.text_area :title
  .field
    = f.label :details
    %br
    = f.text_area :details
  .field
    = f.check_box :completed
    = f.label :completed, 'Completed?'
  .actions
    = f.submit "Update dream"