config/routes.rb
Dreamscape::Application.routes.draw do

  resources :tasks, :only => [:edit, :update, :create, :destroy]
  resources :dreams, :only => [:edit, :update, :create, :destroy]
  resources :collaborations, :only => ['create', 'destroy']
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "pages/index"
  post "pages/index"
  root :to => 'pages#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :dream

  has_many :assignments, :dependent => :destroy
  has_many :assignees, :through => :assignments, :source => :assignee

  validates :user_id, :presence => true
  validates :title,   :presence => true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :init_facebook_oauth, :force_facebook_auth, :init_facebook_crap
  before_filter :set_task, :only => [:edit, :update]
  before_filter :check_collaborators, :only => [:edit, :update]

  def create
    dream_id = Integer(params[:task][:dream_id])
    dream = Dream.find(dream_id)
    
    collabs = dream.collaborators
    redirect_to root_path unless dream.user == current_user || collabs.include?(current_user)

    @task = dream.tasks.build(params[:task])
    @task.user = current_user
    if @task.save
      redirect_to root_path, :flash => { :success => "Task created!" }
    else
      @dream = Dream.new
      @dreams = current_user.dreams
      render 'pages/index'
    end
  end

  def edit
    @friends = current_user.friends.map { |fr| [fr.name, fr.id] }
    @friends.unshift([current_user.name, current_user.id])
  end

  def update
    if @task.update_attributes(params[:task])
      assignee_ids = params[:assignee_ids]
      assignees = @task.assignees
      unless assignee_ids.nil?
        assignee_ids.each do |id|
          @task.assignments.create!({:assignee_id => id}) if assignees.find_by_id(id).nil?
        end
      end
      flash[:success] = "Task updated."
      redirect_to '/pages/index'
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find_by_id(params[:id])
    @task.destroy
    redirect_to root_path, :flash => {:success => "Task deleted!"}
  end

  private

  def set_task
    @task = Task.find_by_id(params[:id])
  end

  def check_collaborators
    collabs = @task.dream.collaborators
    redirect_to root_path unless @task.dream.user == current_user || @task.user == current_user || collabs.include?(current_user)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.haml
%div{:class => "task"}
  %h4= task.title
  =link_to "Edit", edit_task_path(task)
  =link_to "Delete", task, :method => :delete
  - if task.completed?
    =link_to "Incomplete", {:controller => "tasks", :action => "update", "task" => {:completed => false}, :id => task.id}, :method => :put
  - else
    =link_to "Complete", {:controller => "tasks", :action => "update", "task" => {:completed => true}, :id => task.id}, :method => :put

app/views/tasks/edit.html.haml
= form_for(@task) do |f|
  = render('shared/error_messages', :object => f.object)
  .field
    = f.label :title
    %br
    = f.text_area :title, :class => 'title'
  .field
    = f.label :details
    %br
    = f.text_area :details
  .field
    = f.label :assignees, 'Assignees'
    %br
    = select_tag("assignee_ids[]", options_for_select(@friends, @task.assignees.map { |a| a.id }), {:multiple => true, :size => 6})
  .field
    = f.check_box :completed
    = f.label :completed, 'Completed?'
  .actions
    = f.submit "Update task"